<?php

use Illuminate\Database\Seeder;

class stumapseed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stumap')->TRUNCATE();

        DB::table('stumap')->insert(
        [

            [
                'team_no'=>'1',
                'name'=>'sparkle8424',
                'stuid'=>'B10231014'
            ],
            [
                'team_no'=>'1',
                'name'=>'fatgoldencat',
                'stuid'=>'B10231001'
            ],
            [
                'team_no'=>'1',
                'name'=>'Erinzzhang',
                'stuid'=>'B10231030'
            ],
            [
                'team_no'=>'2',
                'name'=>'hijann',
                'stuid'=>'B10030018'
            ],
            [
                'team_no'=>'2',
                'name'=>'tina850506',
                'stuid'=>'B10333003'
            ],
            [
                'team_no'=>'2',
                'name'=>'maple580122',
                'stuid'=>'B10333014'
            ],
            [
                'team_no'=>'2',
                'name'=>'wuyiru0820',
                'stuid'=>'B10333034'
            ],
            [
                'team_no'=>'3',
                'name'=>'susanh1027',
                'stuid'=>'B10330335'
            ],
            [
                'team_no'=>'3',
                'name'=>'yuyenyen',
                'stuid'=>'B10330331'
            ],
            [
                'team_no'=>'3',
                'name'=>'aakki957',
                'stuid'=>'B10330313'
            ],
            [
                'team_no'=>'3',
                'name'=>'iop123016k',
                'stuid'=>'B10330324'
            ],
            [
                'team_no'=>'4',
                'name'=>'supernisor123',
                'stuid'=>'B10230230'
            ],
            [
                'team_no'=>'4',
                'name'=>'kevinmyexp',
                'stuid'=>'B10130210'
            ],
            [
                'team_no'=>'4',
                'name'=>'mantawu30',
                'stuid'=>'B10134007'
            ],
            [
                'team_no'=>'4',
                'name'=>'trylovetom',
                'stuid'=>'B10202012'
            ],
            [
                'team_no'=>'5',
                'name'=>'ycpss5612970',
                'stuid'=>'B10209040'
            ],
            [
                'team_no'=>'5',
                'name'=>'',
                'stuid'=>'B10309037'
            ],
            [
                'team_no'=>'5',
                'name'=>'',
                'stuid'=>'B10309032'
            ],
            [
                'team_no'=>'5',
                'name'=>'williamchi1996',
                'stuid'=>'B10309011'
            ],
            [
                'team_no'=>'6',
                'name'=>'ppeennyy',
                'stuid'=>'B10217023'
            ],
            [
                'team_no'=>'6',
                'name'=>'Minima1231',
                'stuid'=>'B10217031'
            ],
            [
                'team_no'=>'6',
                'name'=>'',
                'stuid'=>'M10308008'
            ],
            [
                'team_no'=>'6',
                'name'=>'BomboButt',
                'stuid'=>'B10202009'
            ],
            [
                'team_no'=>'7',
                'name'=>'lioupeipei',
                'stuid'=>'B10108036'
            ],
            [
                'team_no'=>'7',
                'name'=>'zheng-xun',
                'stuid'=>'B10130326'
            ],
            [
                'team_no'=>'7',
                'name'=>'calx3eung',
                'stuid'=>'F10415012'
            ],
            [
                'team_no'=>'8',
                'name'=>'arthur55',
                'stuid'=>'B10309020'
            ],
            [
                'team_no'=>'8',
                'name'=>'tom20314',
                'stuid'=>'B10309004'
            ],
            [
                'team_no'=>'8',
                'name'=>'sjjt0816',
                'stuid'=>'B10309029'
            ],
            [
                'team_no'=>'8',
                'name'=>'Edward14',
                'stuid'=>'B10309014'
            ],
            [
                'team_no'=>'9',
                'name'=>'MickeyXie',
                'stuid'=>'F10402010'
            ],
            [
                'team_no'=>'9',
                'name'=>'BLGEric',
                'stuid'=>'B10201006'
            ],
            [
                'team_no'=>'9',
                'name'=>'yoyoown',
                'stuid'=>'A10409003'
            ],
            [
                'team_no'=>'10',
                'name'=>'james850803',
                'stuid'=>'B10330243'
            ],
            [
                'team_no'=>'10',
                'name'=>'ssy8762',
                'stuid'=>'B10330312'
            ],
            [
                'team_no'=>'10',
                'name'=>'ringmoon308',
                'stuid'=>'B10330327'
            ],
            [
                'team_no'=>'10',
                'name'=>'yyy22227',
                'stuid'=>'B10330310'
            ],
            [
                'team_no'=>'11',
                'name'=>'zxa011023',
                'stuid'=>'B10309028'
            ],
            [
                'team_no'=>'11',
                'name'=>'karen840225',
                'stuid'=>'B10309001'
            ],
            [
                'team_no'=>'11',
                'name'=>'hank321',
                'stuid'=>'B10309017'
            ],
            [
                'team_no'=>'11',
                'name'=>'Sylviachang',
                'stuid'=>'B10301002'
            ],
            [
                'team_no'=>'12',
                'name'=>'Rashine',
                'stuid'=>'B10107108'
            ],
            [
                'team_no'=>'12',
                'name'=>'Lin-Wang-Yang',
                'stuid'=>'B10131010'
            ],
            [
                'team_no'=>'14',
                'name'=>'1anmiao',
                'stuid'=>'B10430032'
            ],
            [
                'team_no'=>'14',
                'name'=>'KuPao/',
                'stuid'=>'B10430029'
            ],
            [
                'team_no'=>'14',
                'name'=>'Eli-lin',
                'stuid'=>'B10430447'
            ],
            [
                'team_no'=>'14',
                'name'=>'B10430019',
                'stuid'=>'B10430019'
            ],
            [
                'team_no'=>'14',
                'name'=>'KafitLee',
                'stuid'=>'B10430036'
            ],
            [
                'team_no'=>'14',
                'name'=>'JuiYun-Chang',
                'stuid'=>'B10430015'
            ],
            [
                'team_no'=>'15',
                'name'=>'iris-iriswang',
                'stuid'=>'B10309007'
            ],
            [
                'team_no'=>'15',
                'name'=>'KamiSP',
                'stuid'=>'B10309040'
            ],
            [
                'team_no'=>'15',
                'name'=>'cindy24678',
                'stuid'=>'B10309024'
            ],
            [
                'team_no'=>'16',
                'name'=>'Yami_Yona',
                'stuid'=>'B10309005'
            ],
            [
                'team_no'=>'16',
                'name'=>'miraclechen',
                'stuid'=>'B10309026'
            ],
            [
                'team_no'=>'16',
                'name'=>'charlotte0731',
                'stuid'=>'B10309016'
            ],
            [
                'team_no'=>'16',
                'name'=>'chelseaholyvia',
                'stuid'=>'B10309044'
            ],
            [
                'team_no'=>'17',
                'name'=>'Tyler0127',
                'stuid'=>'B10309012'
            ],
            [
                'team_no'=>'17',
                'name'=>'',
                'stuid'=>'B10309019'
            ],
            [
                'team_no'=>'17',
                'name'=>'kicatller6',
                'stuid'=>'B10309031'
            ],
            [
                'team_no'=>'17',
                'name'=>'aschlu',
                'stuid'=>'B10309043'
            ],
            [
                'team_no'=>'18',
                'name'=>'k402xxxcenxxx',
                'stuid'=>'B10232034'
            ],
            [
                'team_no'=>'18',
                'name'=>'hank20219',
                'stuid'=>'B10232011'
            ],
            [
                'team_no'=>'18',
                'name'=>'pineapplekao',
                'stuid'=>'B10330002'
            ],
            [
                'team_no'=>'18',
                'name'=>'mousems',
                'stuid'=>'B10115012'
            ],
            [
                'team_no'=>'19',
                'name'=>'lf2netr0',
                'stuid'=>'B10309002'
            ],
            [
                'team_no'=>'19',
                'name'=>'MeiSee',
                'stuid'=>'B10309008'
            ],
            [
                'team_no'=>'19',
                'name'=>'balabagi2012',
                'stuid'=>'B10309009'
            ],
            [
                'team_no'=>'19',
                'name'=>'giggy1234567',
                'stuid'=>'B10309027'
            ],
            [
                'team_no'=>'20',
                'name'=>'miles0930',
                'stuid'=>'B10309006'
            ],
            [
                'team_no'=>'20',
                'name'=>'monyang',
                'stuid'=>'B10309041'
            ],
            [
                'team_no'=>'20',
                'name'=>'sunnyme',
                'stuid'=>'B10309042'
            ],
            [
                'team_no'=>'21',
                'name'=>'Ningster',
                'stuid'=>'M10409218'
            ]
        ]);
    }
}
